### PR TITLE
Allow single resources to be updated

### PR DESCRIPTION
**Pull request by EddyCMWF**
Single resources can be provided to the update-catalogue entry_point

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-projects/cads-catalogue?pullRequest=97) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-projects/cads-catalogue?pullRequest=97) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-projects/cads-catalogue?pullRequest=97) it.</sub>

**Comment by EddyCMWF** [comment]
Furthermore, the functionality could be expanded to only update resources which have changed.
The current implementation is that if a single resource is changed, then we update the whole catalogue.

**Comment by EddyCMWF** [comment]
Okay, this needs more work, current implementation removes all the other datasets

**Comment by alex75** [comment]
> This needs more work, current implementation removes all the other datasets

yes, when you select the resources to be updated, the functionality to remove the uninvolved resources should be disabled. Ok

**Comment by alex75** [comment]
> Furthermore, the implementation could be expanded to only update resources which have changed. The current implementation is that if a single resource is changed, then we update the whole catalogue.



> Furthermore, the implementation could be expanded to only update resources which have changed. The current implementation is that if a single resource is changed, then we update the whole catalogue.

Yes and no. Inside each dataset record we store also the hash of its cads-forms-json folder, so if the hash is not changed, the update of that dataset is skipped. This skipping is disabled only in case you use 'the force' or if the cads-catalogue's git commit has changed

**Comment by alex75** [comment]
Close, as duplicated of https://github.com/ecmwf-projects/cads-catalogue/pull/101

**Pull request closed without merging**
